# -*- coding: utf-8 -*-
"""starcoder2_java2python_ast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2hoSMC8IOJHEV6lAZtKl9QQfqJBHz4J
"""

!pip install -q datasets==3.6.0
!pip install -q -U bitsandbytes>=0.46.1
!pip install -q transformers peft accelerate bitsandbytes
!pip install tree-sitter
!pip install tree-sitter-java
!pip install tree-sitter-python

from transformers import AutoTokenizer, AutoModel, AutoModelForCausalLM, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig, PeftModel
from google.colab import userdata
import datasets
from datasets import load_dataset, Dataset
import torch
import pandas as pd
import tree_sitter
import ast
import json
from tree_sitter import Language, Parser
import tree_sitter_java
import tree_sitter_python

print(datasets.__version__)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)

HF_TOKEN = userdata.get('HF_TOKEN')
device = "cuda" if torch.cuda.is_available() else "cpu"
model_name = "bigcode/starcoder2-3b"

tokenizer = AutoTokenizer.from_pretrained(model_name, token=HF_TOKEN)
model = AutoModelForCausalLM.from_pretrained(model_name, token=HF_TOKEN, quantization_config=bnb_config).to(device)

!unzip -o /content/starcoder2-python-java-custom-lora.zip -d /content/starcoder2-python-java-custom-lora/

# Load the LoRA adapters from the checkpoint
model_to_test = PeftModel.from_pretrained(model, "/content/starcoder2-python-java-custom-lora")

# Set the model to evaluation mode and move to device
model_to_test = model_to_test.eval().to(device)

print("Model loaded successfully for testing.")

def generate_solution(prompt, num_solutions=1):
    full_prompt = f"""
             ### Instruction
             {prompt}
             ### Response
             """

    inputs = tokenizer(full_prompt, return_tensors="pt").to(device)

    # #Greedy decoding
    # outputs = model_to_test.generate(
    # **inputs,
    # max_new_tokens=300,
    # do_sample=False,
    #repetition_penalty=1.2,
    #num_return_sequences=num_solutions,
    # eos_token_id=tokenizer.eos_token_id,
    # pad_token_id=tokenizer.eos_token_id

    # )

    #Low temperature
    outputs = model_to_test.generate(
        **inputs,
        max_new_tokens=300,
        do_sample=True,
        temperature=0.2,
        top_p=0.95,
        #repetition_penalty=1.2,
        num_return_sequences=num_solutions,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id
    )

    # for pass@10, 20
    # outputs = model_to_test.generate(
    #     **inputs,
    #     max_new_tokens=300,
    #     do_sample=True, # Enable sampling for diverse solutions
    #     temperature=0.7, # Add temperature for diversity
    #     num_return_sequences=num_solutions, # Generate multiple solutions
    #     eos_token_id=tokenizer.eos_token_id
    # )

    # Decode all generated sequences
    generated_texts = [tokenizer.decode(output, skip_special_tokens=True) for output in outputs]

    return generated_texts

def extract_code(text):
    if "### Response" in text:
        return text.split("### Response")[-1].strip()

    return text.strip()

def run_mbpp_tests(code, test_list):
    namespace = {}

    try:
        exec(code, namespace)

        for test in test_list:
            exec(test, namespace)

        return True

    except Exception:
        return False

JAVA_LANGUAGE = Language(
    tree_sitter_java.language()
)

parser = Parser()
parser.language = JAVA_LANGUAGE

def extract_java_ir(code):

    tree = parser.parse(
        bytes(code, "utf8")
    )

    root = tree.root_node

    ir = {
        "functions": 0,
        "for_loops": 0,
        "while_loops": 0,
        "ifs": 0,
        "returns": 0,
        "assignments": 0,
        "binary_ops": [],
        "comparisons": [],
        "calls": [],
        "data_structures": [],
        "recursion": False
    }

    method_names = set()

    def walk(node):

        if node.type == "method_declaration":

            ir["functions"] += 1

            for child in node.children:

                if child.type == "identifier":
                    method_names.add(
                        child.text.decode()
                    )

        elif node.type in [
            "for_statement",
            "enhanced_for_statement"
        ]:
            ir["for_loops"] += 1

        elif node.type == "while_statement":
            ir["while_loops"] += 1

        elif node.type == "if_statement":
            ir["ifs"] += 1

        elif node.type == "return_statement":
            ir["returns"] += 1

        elif node.type == "assignment_expression":
            ir["assignments"] += 1

        elif node.type == "method_invocation":

            for child in node.children:

                if child.type == "identifier":

                    name = child.text.decode()

                    ir["calls"].append(name)

                    if name in method_names:
                        ir["recursion"] = True

                    break

        elif node.type in [
            "+",
            "-",
            "*",
            "/",
            "%",
            "==",
            "!=",
            "<",
            ">",
            "<=",
            ">="
        ]:
            ir["binary_ops"].append(
                node.type
            )

        elif node.type == "array_creation_expression":
            ir["data_structures"].append(
                "array"
            )

        for child in node.children:
            walk(child)

    walk(root)

    for key in [
        "binary_ops",
        "comparisons",
        "calls",
        "data_structures"
    ]:
        ir[key] = sorted(
            list(set(ir[key]))
        )

    return ir

import ast

def extract_python_ir(code):

    tree = ast.parse(code)

    ir = {
        "functions": 0,
        "for_loops": 0,
        "while_loops": 0,
        "ifs": 0,
        "returns": 0,
        "assignments": 0,
        "binary_ops": [],
        "comparisons": [],
        "calls": [],
        "data_structures": [],
        "recursion": False
    }

    function_names = set()

    class Visitor(ast.NodeVisitor):

        def visit_FunctionDef(self, node):

            ir["functions"] += 1
            function_names.add(node.name)

            self.generic_visit(node)

        def visit_For(self, node):
            ir["for_loops"] += 1
            self.generic_visit(node)

        def visit_While(self, node):
            ir["while_loops"] += 1
            self.generic_visit(node)

        def visit_If(self, node):
            ir["ifs"] += 1
            self.generic_visit(node)

        def visit_Return(self, node):
            ir["returns"] += 1
            self.generic_visit(node)

        def visit_Assign(self, node):
            ir["assignments"] += 1
            self.generic_visit(node)

        def visit_Call(self, node):

            if isinstance(node.func, ast.Name):

                ir["calls"].append(node.func.id)

                if node.func.id in function_names:
                    ir["recursion"] = True

            self.generic_visit(node)

        def visit_BinOp(self, node):

            op = type(node.op).__name__

            ir["binary_ops"].append(op)

            self.generic_visit(node)

        def visit_Compare(self, node):

            for op in node.ops:
                ir["comparisons"].append(
                    type(op).__name__
                )

            self.generic_visit(node)

        def visit_List(self, node):
            ir["data_structures"].append("list")
            self.generic_visit(node)

        def visit_Dict(self, node):
            ir["data_structures"].append("dict")
            self.generic_visit(node)

        def visit_Set(self, node):
            ir["data_structures"].append("set")
            self.generic_visit(node)

        def visit_Tuple(self, node):
            ir["data_structures"].append("tuple")
            self.generic_visit(node)

    Visitor().visit(tree)

    for key in [
        "binary_ops",
        "comparisons",
        "calls",
        "data_structures"
    ]:
        ir[key] = sorted(list(set(ir[key])))

    return ir

def similarity(ir1, ir2):

    score = 0
    total = 0

    numeric_fields = [
        "functions",
        "for_loops",
        "while_loops",
        "ifs",
        "returns",
        "assignments"
    ]

    for field in numeric_fields:

        total += 1

        if ir1[field] == ir2[field]:
            score += 1

    list_fields = [
        "binary_ops",
        "comparisons",
        "calls",
        "data_structures"
    ]

    for field in list_fields:

        total += 1

        s1 = set(ir1[field])
        s2 = set(ir2[field])

        union = s1.union(s2)

        if len(union) == 0:
            score += 1
        else:
            score += (
                len(s1.intersection(s2))
                / len(union)
            )

    total += 1

    if ir1["recursion"] == ir2["recursion"]:
        score += 1

    return round(score / total, 4)

def compare_java_python(java_problem, python_code):
    java_ir = extract_java_ir(java_problem)
    python_ir = extract_python_ir(python_code)

    score = similarity(
        java_ir,
        python_ir
    )
    print(f"Similarity: {score}")
    return score

translation_pairs_df = pd.read_csv('/content/java_python_translation_pairs_corrected.csv')
display(translation_pairs_df.head())

results_data = []

for index, row in translation_pairs_df.iterrows():
    java_problem_text = f"""
    convert the following java code to python
    {row['java_code']}
    """
    java_problem = row['java_code']
    python_solution_original = row['python_code'] # Keep original Python solution

    # Generate Python solution
    generated_solutions = generate_solution(java_problem_text, num_solutions=1)
    generated_python_code = extract_code(generated_solutions[0])

    # Calculate similarity score
    try:
        score = compare_java_python(java_problem, generated_python_code)
    except Exception as e:
        score = 0.0 # Assign a default score if an error occurs during comparison
        print(f"Error calculating similarity for qid {row['qid']}: {e}")

    # Collect all data for the new DataFrame
    results_data.append({
        'qid': row['qid'],
        'text': row['text'], # Include original 'text' column if desired
        'java_code': java_problem,
        'python_code_original': python_solution_original,
        'generated_python_code': generated_python_code,
        'ast_similarity_score': score
    })

results_df = pd.DataFrame(results_data)

print("Processing complete. Displaying the new DataFrame with results:")
display(results_df.head())

"""### Calculating CodeBLEU, CodeBERT, and ROUGE scores"""

!pip install -q evaluate sentence-transformers nltk

!pip install rouge_score

import evaluate
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import nltk

# Download necessary NLTK data for BLEU (if not already present)
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

# Load BLEU and ROUGE metrics
bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")

# Load a SentenceTransformer model for CodeBERT-like embeddings
# Using a general-purpose model; for true CodeBERT, a code-specific model would be better if available via SentenceTransformers
# For better performance on code, consider models like 'sentence-transformers/all-distilroberta-v1' or a fine-tuned code model.
embedding_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

def calculate_code_metrics(reference_code, generated_code):
    # BLEU score
    # The 'evaluate' library expects lists of strings for references and predictions
    # For a single pair, we wrap them in lists
    bleu_score = bleu.compute(predictions=[generated_code], references=[[reference_code]])

    # ROUGE score
    rouge_score = rouge.compute(predictions=[generated_code], references=[reference_code])

    # CodeBERT-like similarity using sentence embeddings
    # Generate embeddings for both original and generated code
    embeddings_ref = embedding_model.encode(reference_code, convert_to_tensor=True)
    embeddings_gen = embedding_model.encode(generated_code, convert_to_tensor=True)

    # Calculate cosine similarity
    # Reshape for sklearn's cosine_similarity if they are 1D tensors/arrays
    if embeddings_ref.dim() == 1:
        embeddings_ref = embeddings_ref.unsqueeze(0)
    if embeddings_gen.dim() == 1:
        embeddings_gen = embeddings_gen.unsqueeze(0)

    codebert_similarity = cosine_similarity(embeddings_ref.cpu(), embeddings_gen.cpu())[0][0]

    return {
        'bleu': bleu_score['bleu'],
        'rouge1': rouge_score['rouge1'],
        'rouge2': rouge_score['rouge2'],
        'rougeL': rouge_score['rougeL'],
        'codebert_similarity': float(codebert_similarity)
    }

# Initialize new columns
results_df['bleu_score'] = 0.0
results_df['rouge1_score'] = 0.0
results_df['rouge2_score'] = 0.0
results_df['rougeL_score'] = 0.0
results_df['codebert_similarity_score'] = 0.0

print("Calculating additional metrics for results_df...")

# Iterate and calculate scores, updating the DataFrame
for idx, row in results_df.iterrows():
    ref_code = row['python_code_original']
    gen_code = row['generated_python_code']

    metrics = calculate_code_metrics(ref_code, gen_code)

    results_df.at[idx, 'bleu_score'] = metrics['bleu']
    results_df.at[idx, 'rouge1_score'] = metrics['rouge1']
    results_df.at[idx, 'rouge2_score'] = metrics['rouge2']
    results_df.at[idx, 'rougeL_score'] = metrics['rougeL']
    results_df.at[idx, 'codebert_similarity_score'] = metrics['codebert_similarity']

print("Metrics calculation complete. Displaying updated DataFrame head:")
display(results_df.head())

"""### Calculating Composite Translation Score"""

results_df["translation_score"] = (
    0.35 * results_df["codebert_similarity_score"] +
    0.25 * results_df["ast_similarity_score"] +
    0.15 * results_df["rougeL_score"] +
    0.10 * results_df["rouge1_score"] +
    0.05 * results_df["rouge2_score"] +
    0.10 * results_df["bleu_score"]
)

print("Composite translation score calculated with new weights. Displaying updated DataFrame head:")
display(results_df.head())

"""### Mean Scores"""

mean_translation_score = results_df['translation_score'].mean()
mean_codebert_similarity = results_df['codebert_similarity_score'].mean()
mean_ast_similarity = results_df['similarity_score'].mean()
mean_rougeL = results_df['rougeL_score'].mean()
mean_rouge1 = results_df['rouge1_score'].mean()
mean_rouge2 = results_df['rouge2_score'].mean()
mean_bleu = results_df['bleu_score'].mean()

print(f"Mean Translation Score: {mean_translation_score:.4f}")
print(f"Mean CodeBERT Similarity Score: {mean_codebert_similarity:.4f}")
print(f"Mean AST Similarity Score: {mean_ast_similarity:.4f}")
print(f"Mean ROUGE-L Score: {mean_rougeL:.4f}")
print(f"Mean ROUGE-1 Score: {mean_rouge1:.4f}")
print(f"Mean ROUGE-2 Score: {mean_rouge2:.4f}")
print(f"Mean BLEU Score: {mean_bleu:.4f}")